[package]
name = "moonlapse-client"
version = "0.1.0"
edition = "2024"

[dependencies]
moonlapse-shared = { path = "../moonlapse-shared" }
ratatui = "0.29.0"
anyhow = "1.0.100"
env_logger = "0.11.8"
log = "0.4.28"